name: pypi-release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Build and publish to PyPI
        uses: serapeum-org/github-actions/actions/release/pypi@38c111084f99d5ff5f4a1e63bedce48fe33a10c0 # pypi-release/v1.0.3
        with:
          pypi-username: __token__
          pypi-password: ${{ secrets.PYPI_PUBLISH }}
          package-manager: 'pixi'
          install-groups: 'dev'
          verify-lock: 'false'
